const fruit = [
  {
    id: 1,
    name: "Apple",
    category: "Fruits",
    price: 1.5,
    currency: "USD",
    description: "Fresh and crisp apples from organic farms.",
    stock: true,
    rating: 4.5,
    image: "apple.jpg",
  },
  {
    id: 2,
    name: "Cherry",
    category: "Fruits",
    price: 0.5,
    currency: "USD",
    description: "Ripe Cherry, perfect for a healthy snack.",
    stock: true,
    rating: 4.2,
    image: "cherry.jpg",
  },
  {
    id: 3,
    name: "Orange",
    category: "Fruits",
    price: 1.0,
    currency: "USD",
    description: "Sweet and juicy oranges, packed with vitamin C.",
    stock: true,
    rating: 4.7,
    image: "oranges.jpg",
  },
  {
    id: 4,
    name: "Mango",
    category: "Fruits",
    price: 2.0,
    currency: "USD",
    description: "Delicious tropical mangoes, full of flavor.",
    stock: false,
    rating: 4.8,
    image: "mango.jpg",
  },
  {
    id: 5,
    name: "Pineapple",
    category: "Fruits",
    price: 3.0,
    currency: "USD",
    description: "Tangy and sweet pineapples, great for smoothies.",
    stock: true,
    rating: 4.6,
    image: "pineapple.jpg",
  },
  {
    id: 6,
    name: "Strawberry",
    category: "Berries",
    price: 4.0,
    currency: "USD",
    description: "Fresh strawberries, perfect for desserts and salads.",
    stock: true,
    rating: 4.9,
    image: "strawberry.jpg",
  },
  {
    id: 7,
    name: "Kiwi",
    category: "Fruits",
    price: 5.0,
    currency: "USD",
    description: "Sweet and nutritious blueberries, high in antioxidants.",
    stock: true,
    rating: 4.7,
    image: "kiwi.jpg",
  },
  {
    id: 8,
    name: "Watermelon",
    category: "Fruits",
    price: 7.0,
    currency: "USD",
    description: "Large, refreshing watermelons, perfect for summer.",
    stock: false,
    rating: 4.5,
    image: "watermelon.jpg",
  },
  {
    id: 9,
    name: "Grapes",
    category: "Fruits",
    price: 2.5,
    currency: "USD",
    description: "Fresh and juicy grapes, great for snacking or salads.",
    stock: true,
    rating: 4.4,
    image: "grapes.jpg",
  },
  {
    id: 10,
    name: "Papaya",
    category: "Fruits",
    price: 3.5,
    currency: "USD",
    description: "Tropical papayas, delicious and rich in nutrients.",
    stock: true,
    rating: 4.3,
    image: "papaya.jpg",
  },
];
export default fruit;
